#!/usr/bin/env bash
#open /etc/passwd file and read each line
while IFS=: read -r username _ userid _ _ homedir _; do
echo "Username: $username"
echo "User ID: $userid"
echo "Home Directory: $homedir"
echo ""
done < /etc/passwd
