#!/usr/bin/env bash
#Bash script that tells a story based on /etc/passwd content
while IFS=: read -r username password userid groupid desc homedir shell; do
echo "The user $username is part of the $groupid gand, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user her $desc"
done < /etc/passwd
