#!/usr/bin/env bash
#Bash script that tells a story based on /etc/passwd content
 IFS=":"
while read -r  read -r username password userid groupid desc homedir shell;do
echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here $desc"
done < /etc/passwd
