#!/usr/bin/env bash
#A script to display the content of current working directory in a list format

for file in *; do
  
  if [[ -f "$file" ]]; then
    
    new_name="${file#*-}"
    

    if [[ "$new_name" != "$file" ]]; then
      echo "$new_name"
    else
      echo "$file"
    fi
  fi
done
