#!/usr/bin/env bash
#checking the file 
a=school
if [ -e $a ]; then
echo "school file exists"
else
echo "school file does not exists"
fi
if [ -s $a ]; then
	echo "school file is not empty"
else
	echo "school file is empty"
fi
if [ -f $a ]; then
	echo "school is a regular file"
else
	echo " "
fi
